"""
Audio configuration for Buddy Voice Assistant  
Handles device settings, sample rates, VAD/AEC, timeouts, and watchdog intervals
"""

# ==== AUDIO DEVICE CONFIGURATION ====
MIC_DEVICE_INDEX = 60
MIC_SAMPLE_RATE = 48000
SAMPLE_RATE = 16000
CHANNELS = 1

# ==== AUDIO BUFFER SETTINGS ====
AUDIO_BUFFER_SIZE = 1024
PROCESSING_CHUNK_SIZE = 160
AUDIO_BUFFER_SIZE_INTERACTIONS = 10

# ==== TIMEOUT CONFIGURATIONS ====  
TRAINING_OFFER_TIMEOUT = 30  # Seconds to wait for training response
SPEECHBRAIN_TIMEOUT = 10     # Model loading timeout
CONVERSATION_TURN_SWITCH_DELAY = 0.3
USER_SPEECH_END_DELAY = 1.2  # Longer delay to ensure speech ended

# ==== WATCHDOG SETTINGS ====
WATCHDOG_INTERVAL_S = 10.0   # Print health status every 10 seconds
WATCHDOG_ENABLED = True

# ==== VAD (Voice Activity Detection) SETTINGS ====
USER_SPEECH_THRESHOLD = 800
USER_MIN_SPEECH_FRAMES = 5
USER_MAX_SILENCE_FRAMES = 20
BUDDY_INTERRUPT_THRESHOLD = 2500
BUDDY_INTERRUPT_GRACE_PERIOD = 1.0

VAD_THRESHOLD = USER_SPEECH_THRESHOLD  # Legacy compatibility
MIN_SPEECH_FRAMES = USER_MIN_SPEECH_FRAMES
MAX_SILENCE_FRAMES = USER_MAX_SILENCE_FRAMES
INTERRUPT_THRESHOLD = BUDDY_INTERRUPT_THRESHOLD

VAD_ONLY_DURING_BUDDY_SPEECH = True
DISABLE_VAD_DURING_USER_TURN = True
ENABLE_VAD_DURING_BUDDY_TURN = True
FAST_VAD_PROCESSING = True

# ==== AEC (Acoustic Echo Cancellation) SETTINGS ====
AEC_ENABLED = True
AEC_AGGRESSIVE_MODE = False
AEC_CONSERVATIVE_MODE = True
AEC_ADAPTATION_RATE = 0.05
AEC_SUPPRESSION_FACTOR = 0.3
AEC_VOICE_PROTECTION = True
AEC_ONLY_DURING_BUDDY_SPEECH = True
DISABLE_AEC_DURING_USER_TURN = True

# ==== AEC SYSTEM SELECTION ====
USE_SMART_AEC_ONLY = True
DISABLE_FULL_DUPLEX_AEC = False
DISABLE_BASIC_AEC = True

# ==== VOICE QUALITY THRESHOLDS ====
VOICE_QUALITY_THRESHOLD = 0.25
SPECTRAL_VOICE_THRESHOLD = 0.35
VOICE_CONFIDENCE_THRESHOLD = 0.75
VOICE_SIMILARITY_BUFFER = 5
BUDDY_VOICE_THRESHOLD = 0.99

# ==== ADVANCED AUDIO ANALYSIS ====
ENABLE_ZCR_ANALYSIS = True       # Zero crossing rate (voice vs noise)
ENABLE_MFCC_ANALYSIS = True      # Mel-frequency analysis
ENABLE_PITCH_DETECTION = True    # Pitch detection for voice
ENABLE_HARMONIC_ANALYSIS = True  # Harmonic content analysis

# ==== PROFESSIONAL AUDIO QUALITY ====
PROFESSIONAL_AUDIO_QUALITY = True
AUDIO_SMOOTHING = True
SPEECH_ENHANCEMENT = True
NATURAL_INTONATION = True

# ==== DEBUGGING AND MONITORING ====
SAVE_DEBUG_AUDIO = True
SHOW_AEC_STATS = True
MONITOR_VOICE_QUALITY = True
LOG_VOLUME_LEVELS = False
SHOW_NOISE_ANALYSIS = True
SHOW_VOICE_QUALITY_SCORES = True
LOG_REJECTION_REASONS = True

# ==== PERFORMANCE SETTINGS ====
REDUCED_CPU_MODE = False
HUMAN_SPEECH_PROTECTION = True
MINIMAL_PROCESSING_MODE = True
SPEECH_QUALITY_PRIORITY = True
HUMAN_VOICE_PRIORITY = True

# ==== PASSIVE AUDIO BUFFERING ====
PASSIVE_AUDIO_BUFFERING = True
PASSIVE_SAMPLE_COLLECTION = True
BACKGROUND_VOICE_LEARNING = True

# ==== AUDIO ENVIRONMENT SETTINGS ====
AUDIO_ENVIRONMENT_ANALYSIS = True
SPEAKING_CONFIDENCE_ANALYSIS = True
TEXT_CLARITY_ANALYSIS = True
SESSION_PATTERN_LEARNING = True

# ==== SPEECH PADDING ====
SPEECH_PADDING_START = 0.8
SPEECH_PADDING_END = 0.8
WHISPER_CONTEXT_PADDING = 3.0

def startup_summary():
    """Print startup summary for audio configuration"""
    print(f"[Config-Audio] 🎤 AUDIO SYSTEM CONFIGURATION:")
    print(f"  Device Index: {MIC_DEVICE_INDEX}")
    print(f"  Sample Rate: {SAMPLE_RATE} Hz")
    print(f"  Buffer Size: {AUDIO_BUFFER_SIZE}")
    print(f"  Speech Threshold: {USER_SPEECH_THRESHOLD}")
    print(f"  Voice Quality Threshold: {VOICE_QUALITY_THRESHOLD}")
    print(f"  Spectral Voice Threshold: {SPECTRAL_VOICE_THRESHOLD}")
    print(f"  Interrupt Threshold: {BUDDY_INTERRUPT_THRESHOLD}")
    print(f"  VAD Enabled: {not DISABLE_VAD_DURING_USER_TURN}")
    print(f"  AEC Enabled: {AEC_ENABLED}")
    print(f"  Watchdog Interval: {WATCHDOG_INTERVAL_S}s")
    print(f"  Professional Quality: {PROFESSIONAL_AUDIO_QUALITY}")
    print(f"  Audio Smoothing: {AUDIO_SMOOTHING}")